### ISSUE TITLE
RuntimeError: shape mismatch: value tensor of shape [49, 1536] cannot be broadcast to indexing result of shape [0, 1536]

### ISSUE THREAD

**Issue by anshkumar** [2U1/Qwen2-VL-Finetune#18]
Was doing fine-tunning on my custom dataset. Getting following error:

```
[2024-11-22 16:10:47,569] [WARNING] [engine.py:1179:_do_optimizer_sanity_check] **** You are using ZeRO with an untested optimizer, proceed with caution *****
Parameter Offload: Total persistent parameters: 686592 in 401 params
{'loss': 4.9398, 'grad_norm': 243.39051064272118, 'learning_rate': 1.4005602240896359e-08, 'epoch': 0.0}                                                  
  0%|                                                                                                                | 1/23800 [00:03<25:10:16,  3.81s/it][rank1]: Traceback (most recent call last):
[rank1]:   File "/home/sort/ved/sort/apple_l2/Qwen2-VL-Finetune/src/training/train.py", line 209, in <module>
[rank1]:     train()
[rank1]:   File "/home/sort/ved/sort/apple_l2/Qwen2-VL-Finetune/src/training/train.py", line 184, in train
[rank1]:     trainer.train()
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 2122, in train
[rank1]:     return inner_training_loop(
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 2474, in _inner_training_loop
[rank1]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 3572, in training_step
[rank1]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 3625, in compute_loss
[rank1]:     outputs = model(**inputs)
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank1]:     ret_val = func(*args, **kwargs)
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
[rank1]:     loss = self.module(*inputs, **kwargs)
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank1]:     return inner()
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank1]:     result = forward_call(*args, **kwargs)
[rank1]:   File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/liger_kernel/transformers/model/qwen2_vl.py", line 109, in lce_forward
[rank1]:     inputs_embeds[image_mask] = image_embeds
[rank1]: RuntimeError: shape mismatch: value tensor of shape [49, 1536] cannot be broadcast to indexing result of shape [0, 1536]
W1122 16:10:57.817000 79821 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 79875 closing signal SIGTERM
E1122 16:10:58.032000 79821 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 1 (pid: 79876) of binary: /home/sort/miniconda3/envs/qwen2/bin/python
Traceback (most recent call last):
  File "/home/sort/miniconda3/envs/qwen2/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1165, in launch_command
    multi_gpu_launcher(args)
  File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/accelerate/commands/launch.py", line 799, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sort/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/training/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-22_16:10:57
  host      : sort-X570S-AORUS-MASTER
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 79876)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by anshkumar** [comment]
My custom dataset was missing <image> token in some of the texts.
