### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jhagelback** [2U1/Qwen2-VL-Finetune#19]
I get the following error:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/Qwen2-VL-Finetune/src/training/train.py", line 213, in <module>
[rank0]:     train()
[rank0]:   File "/root/Qwen2-VL-Finetune/src/training/train.py", line 188, in train
[rank0]:     trainer.train()
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 2122, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 2426, in _inner_training_loop
[rank0]:     batch_samples, num_items_in_batch = self.get_batch_samples(epoch_iterator, num_batches)
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 5038, in get_batch_samples
[rank0]:     batch_samples += [next(epoch_iterator)]
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/accelerate/data_loader.py", line 557, in __iter__
[rank0]:     current_batch = next(dataloader_iter)
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/_utils.py", line 715, in reraise
[rank0]:     raise exception
[rank0]: IndexError: Caught IndexError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/root/Qwen2-VL-Finetune/src/training/data.py", line 181, in __getitem__
[rank0]:     gpt_response = sources[j + 1]
[rank0]: IndexError: list index out of range
```

**Comment by jhagelback** [comment]
If I change the row:
`for idx, j in enumerate(range(0, len(sources), 2)):` in data.py to
`for idx, j in enumerate(range(0, len(sources)-1, 2)):`
I get pass this stage, but later get another error:
```
[rank4]: Traceback (most recent call last):
[rank4]:   File "/root/Qwen2-VL-Finetune/src/training/train.py", line 213, in <module>
[rank4]:     train()
[rank4]:   File "/root/Qwen2-VL-Finetune/src/training/train.py", line 188, in train
[rank4]:     trainer.train()
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 2122, in train
[rank4]:     return inner_training_loop(
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 2474, in _inner_training_loop
[rank4]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 3572, in training_step
[rank4]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/transformers/trainer.py", line 3625, in compute_loss
[rank4]:     outputs = model(**inputs)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank4]:     ret_val = func(*args, **kwargs)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
[rank4]:     loss = self.module(*inputs, **kwargs)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank4]:     return inner()
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank4]:     result = forward_call(*args, **kwargs)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/peft/peft_model.py", line 563, in forward
[rank4]:     return self.get_base_model()(*args, **kwargs)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank4]:     return inner()
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank4]:     result = forward_call(*args, **kwargs)
[rank4]:   File "/root/miniconda3/envs/qwen2/lib/python3.10/site-packages/liger_kernel/transformers/model/qwen2_vl.py", line 108, in lce_forward
[rank4]:     inputs_embeds[image_mask] = image_embeds
[rank4]: RuntimeError: shape mismatch: value tensor of shape [1058, 3584] cannot be broadcast to indexing result of shape [0, 3584]
```

**Comment by 2U1** [comment]
Can you check your data format once more? It might be the format of the data.

**Comment by 2U1** [comment]
Closing the issue for no activity.
